# Model arguments
# model_init_kwargs:
model_name_or_path: google/gemma-3-1b-it # change this
model_revision: main
torch_dtype: bfloat16
trust_remote_code: True
attn_implementation: flash_attention_2  #sdpa
# use_peft: True

# Data training arguments
dataset_mixer:
  "./data/prm800k_pref_data/listwise_data_chat_with_labels_4negs_gemma3_mini": 1.0
dataset_splits:
  - train
  - test
preprocessing_num_workers: 1
truncation_side: "left"

# SFT trainer config
dataset_text_field: chosen
packing: false
eval_packing: false
output_dir: ./trained_models/gemma-3-1b-prm800k-mini-sft # change this
num_train_epochs: 1
max_steps: -1
bf16: true
per_device_train_batch_size: 16  # Llama2:12, Llama3: 4
per_device_eval_batch_size: 16  # Llama2:4, Llama3: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
gradient_accumulation_steps: 2
max_grad_norm: 1.0
learning_rate: 5.0e-07
optim: adamw_torch
lr_scheduler_type: cosine
warmup_ratio: 0.1
group_by_length: true
do_eval: true
batch_eval_metrics: true
eval_strategy: "steps"
eval_steps: 10
log_level: info
logging_steps: 5
logging_strategy: steps
max_length: 16192
overwrite_output_dir: true
remove_unused_columns: true
completion_only_loss: true
run_name: gemma-3-1b-prm800k-mini-sft # modelname-size-sft/dpo convention
report_to:
  - "wandb"
save_strategy: "steps"
save_steps: 10
save_only_model: True
save_total_limit: 20
seed: 42
metric_for_best_model: 'perplexity'
greater_is_better: false